name: Build and deploy Node.js app to Azure Web App - react-sovellusmalli-ii

on:
  push:
    branches:
      - authentication
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          if [ -d "dist" ]; then cp -r dist deploy/; fi
          if [ -d "node_modules" ]; then cp -r node_modules deploy/; fi
          cp package.json deploy/
          cp package-lock.json deploy/
          cd deploy
          zip -r ../release.zip .
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d deploy
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'react-sovellusmalli-ii'
          slot-name: 'Production'
          package: ./deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE8BB028A6354FB1B8AEC9F63273F41D }}

      - name: Cleanup
        run: |
          rm -rf deploy
          rm release.zip
